import React, { useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '@/components/AppHeader';
import { colors, spacing, borderRadius } from '@/theme';
import { useAuth } from '@/features/auth/context/AuthContext';
import { donorService } from '../services/donorService';
import type { ChatMessage } from '../types';
export default function ChatScreen() {
  const { donorId = '', donorName = 'Donor' } = useLocalSearchParams<{ donorId: string; donorName: string }>(); const { token, user } = useAuth(); const router = useRouter(); const scroll = useRef<ScrollView>(null); const [chatId, setChatId] = useState(''); const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState('');
  useEffect(() => { void donorService.getChat(token, donorId).then((id) => { setChatId(id); return donorService.messages(token, id); }).then(setMessages); }, [donorId, token]);
  const send = async () => { const clean = text.trim(); if (!clean || !chatId) return; const message = await donorService.sendMessage(token, chatId, clean); setMessages((old) => [...old, message]); setText(''); setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 50); };
  const edit = (message: ChatMessage) => { if (message.senderId !== (user?.id ?? 'me')) return; const next = Platform.OS === 'web' && typeof window !== 'undefined' ? window.prompt('Edit message', message.text) : message.text; if (next && next !== message.text) void donorService.editMessage(token, chatId, message._id, next).then((updated) => setMessages((old) => old.map((m) => m._id === updated._id ? updated : m))); };
  return <KeyboardAvoidingView style={styles.safe} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><AppHeader title={String(donorName)} rightElement={<TouchableOpacity onPress={() => router.push({ pathname: '/call-modal', params: { donorId } })} accessibilityLabel="Start private call"><Ionicons name="call-outline" size={23} color={colors.primary} /></TouchableOpacity>} /><Text style={styles.banner}>{'Phone numbers are hidden for safety.'}</Text><ScrollView ref={scroll} contentContainerStyle={styles.messages}>{messages.map((message) => { const mine = message.senderId === (user?.id ?? 'me'); return <TouchableOpacity key={message._id} onPress={() => edit(message)} onLongPress={() => { if (mine) void donorService.deleteMessage(token, chatId, message._id).then(() => setMessages((old) => old.filter((m) => m._id !== message._id))); }} style={[styles.bubble, mine ? styles.mine : styles.theirs]}><Text style={styles.messageText}>{message.text}</Text><Text style={styles.time}>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text></TouchableOpacity>; })}</ScrollView><View style={styles.composer}><TextInput value={text} onChangeText={setText} maxLength={1000} placeholder="Write a message..." style={styles.input} /><TouchableOpacity onPress={() => { void send(); }} style={styles.send} accessibilityLabel="Send message"><Ionicons name="send" size={20} color={colors.textInverted} /></TouchableOpacity></View></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, banner: { backgroundColor: colors.primaryTonal, color: colors.primaryDark, padding: spacing.sm, textAlign: 'center', fontWeight: '700' }, messages: { padding: spacing.md, gap: spacing.sm, flexGrow: 1 }, bubble: { maxWidth: '80%', padding: spacing.sm, borderRadius: borderRadius.md }, mine: { alignSelf: 'flex-end', backgroundColor: colors.primary }, theirs: { alignSelf: 'flex-start', backgroundColor: colors.card }, messageText: { color: colors.textInverted, flexShrink: 1 }, time: { color: colors.textInverted, opacity: 0.7, fontSize: 10, alignSelf: 'flex-end', marginTop: 3 }, composer: { flexDirection: 'row', alignItems: 'center', padding: spacing.sm, backgroundColor: colors.card, gap: spacing.sm }, input: { flex: 1, minWidth: 0, minHeight: 44, maxHeight: 120, borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.full, paddingHorizontal: spacing.md, color: colors.text }, send: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', flexShrink: 0 } });
