import React, { useEffect, useState } from 'react';
import Slider from '@react-native-community/slider';
import { SafeAreaView, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '@/components/AppHeader';
import { colors, spacing, borderRadius } from '@/theme';
import { useAuth } from '@/features/auth/context/AuthContext';
import { BLOOD_GROUPS, donorStrings } from '../constants';
import { donorService } from '../services/donorService';
import type { BloodGroup, SavedSearch } from '../types';

export default function FindDonorScreen() {
  const router = useRouter(); const { token } = useAuth();
  const [bloodGroup, setBloodGroup] = useState<BloodGroup | null>(null); const [radiusKm, setRadiusKm] = useState(10);
  const [eligibleOnly, setEligibleOnly] = useState(true); const [availableNow, setAvailableNow] = useState(true);
  const [notifyWhenAvailable, setNotifyWhenAvailable] = useState(false);
  const [saved, setSaved] = useState<SavedSearch[]>([]); const [editing, setEditing] = useState<string | undefined>();
  useEffect(() => { void donorService.listSearches(token).then(setSaved); }, [token]);
  const save = async () => { if (!bloodGroup) return; const item = await donorService.saveSearch(token, { bloodGroup, radiusKm, eligibleOnly, availableNow, notifyWhenAvailable }, editing); setSaved((old) => editing ? old.map((s) => s._id === editing ? item : s) : [item, ...old]); setEditing(undefined); };
  const load = (item: SavedSearch) => { setBloodGroup(item.bloodGroup); setRadiusKm(item.radiusKm); setEligibleOnly(item.eligibleOnly); setAvailableNow(item.availableNow); setNotifyWhenAvailable(item.notifyWhenAvailable ?? false); setEditing(item._id); };
  const find = () => router.push({ pathname: '/matching-donors', params: { bloodGroup, radiusKm: String(radiusKm), eligibleOnly: String(eligibleOnly), availableNow: String(availableNow) } });
  return <SafeAreaView style={styles.safe}><AppHeader title={donorStrings.findTitle} showBack={false} rightElement={<TouchableOpacity onPress={() => router.push('/notifications')} accessibilityLabel="Open notifications"><Ionicons name="notifications-outline" size={24} color={colors.text} /></TouchableOpacity>} /><ScrollView contentContainerStyle={styles.content}>
    <Text style={styles.label}>Choose blood group</Text><View style={styles.chips}>{BLOOD_GROUPS.map((group) => <TouchableOpacity key={group} onPress={() => setBloodGroup(group)} style={[styles.chip, bloodGroup === group && styles.chipActive]} accessibilityRole="button"><Text style={[styles.chipText, bloodGroup === group && styles.chipTextActive]}>{group}</Text></TouchableOpacity>)}</View>
    <View style={styles.card}><View style={styles.row}><Text style={styles.label}>Search radius</Text><Text style={styles.value}>{radiusKm} km</Text></View><Slider minimumValue={5} maximumValue={20} step={1} value={radiusKm} onValueChange={setRadiusKm} minimumTrackTintColor={colors.primary} maximumTrackTintColor={colors.primarySoft} thumbTintColor={colors.primary} accessibilityLabel="Search radius" /></View>
    <View style={styles.card}><View style={styles.row}><Text style={styles.option}>Show only eligible donors</Text><Switch value={eligibleOnly} onValueChange={setEligibleOnly} trackColor={{ true: colors.primarySoft }} thumbColor={eligibleOnly ? colors.primary : colors.textMuted} /></View><View style={styles.row}><Text style={styles.option}>Available now</Text><Switch value={availableNow} onValueChange={setAvailableNow} trackColor={{ true: colors.primarySoft }} thumbColor={availableNow ? colors.primary : colors.textMuted} /></View><View style={styles.row}><View style={styles.preferenceCopy}><Text style={styles.option}>Notify when a donor becomes available</Text><Text style={styles.muted}>Get an alert when a matching donor is available.</Text></View><Switch value={notifyWhenAvailable} onValueChange={setNotifyWhenAvailable} trackColor={{ true: colors.primarySoft }} thumbColor={notifyWhenAvailable ? colors.primary : colors.textMuted} /></View></View>
    <TouchableOpacity style={[styles.primaryButton, !bloodGroup && styles.disabled]} disabled={!bloodGroup} onPress={find}><Text style={styles.primaryText}>Find matching donors</Text></TouchableOpacity>
    <View style={styles.savedHeader}><Text style={styles.heading}>Saved searches</Text>{editing ? <TouchableOpacity onPress={() => setEditing(undefined)}><Text style={styles.link}>Cancel edit</Text></TouchableOpacity> : null}</View>
    <TouchableOpacity style={styles.secondaryButton} onPress={() => { void save(); }} disabled={!bloodGroup}><Text style={styles.secondaryText}>{editing ? 'Update saved search' : 'Save this search'}</Text></TouchableOpacity>
    {saved.map((item) => <View style={styles.savedRow} key={item._id}><TouchableOpacity style={{ flex: 1 }} onPress={() => load(item)}><Text style={styles.option}>{item.bloodGroup} • {item.radiusKm} km</Text><Text style={styles.muted}>{item.eligibleOnly ? 'Eligible only' : 'All donors'} • {item.availableNow ? 'Available now' : 'Any availability'}{item.notifyWhenAvailable ? ' • Alerts on' : ''}</Text></TouchableOpacity><TouchableOpacity onPress={() => { void donorService.deleteSearch(token, item._id).then(() => setSaved((old) => old.filter((s) => s._id !== item._id))); }} accessibilityLabel="Delete saved search"><Ionicons name="trash-outline" size={22} color={colors.danger} /></TouchableOpacity></View>)}
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.md, paddingBottom: 40 }, label: { color: colors.textSecondary, fontWeight: '700', marginBottom: spacing.sm }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.md }, chip: { minWidth: 58, minHeight: 44, borderWidth: 1, borderColor: colors.border, borderRadius: borderRadius.full, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.card }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.text, fontWeight: '700' }, chipTextActive: { color: colors.textInverted }, card: { backgroundColor: colors.card, padding: spacing.md, borderRadius: borderRadius.md, marginBottom: spacing.md }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 48 }, preferenceCopy: { flex: 1, minWidth: 0 }, option: { color: colors.text, fontWeight: '600', flexShrink: 1, marginRight: spacing.sm }, value: { color: colors.primary, fontWeight: '800', flexShrink: 0 }, primaryButton: { minHeight: 48, borderRadius: borderRadius.md, backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md }, disabled: { opacity: 0.45 }, primaryText: { color: colors.textInverted, fontWeight: '800', textAlign: 'center' }, secondaryButton: { minHeight: 48, borderRadius: borderRadius.md, borderWidth: 1, borderColor: colors.primary, justifyContent: 'center', alignItems: 'center', marginBottom: spacing.md }, secondaryText: { color: colors.primary, fontWeight: '800', textAlign: 'center' }, heading: { fontSize: 18, fontWeight: '800', color: colors.text }, savedHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: spacing.sm, gap: spacing.sm }, link: { color: colors.primary, fontWeight: '700', flexShrink: 1 }, savedRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card, borderRadius: borderRadius.md, padding: spacing.md, marginBottom: spacing.sm }, muted: { color: colors.textMuted, marginTop: 4, flexShrink: 1 } });
