import React, { useEffect, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '@/components/AppHeader';
import { colors, spacing, borderRadius } from '@/theme';
import { useAuth } from '@/features/auth/context/AuthContext';
import { donorService } from '../services/donorService';
import { exportDonorsPdf } from '../utils/pdf';
import type { BloodGroup, Donor, DonorRequest } from '../types';
export default function MatchingDonorsScreen() {
  const router = useRouter(); const params = useLocalSearchParams<{ bloodGroup: BloodGroup; radiusKm: string; eligibleOnly: string; availableNow: string }>(); const { token } = useAuth();
  const [donors, setDonors] = useState<Donor[]>([]); const [requests, setRequests] = useState<DonorRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { if (!params.bloodGroup) return; Promise.all([donorService.search(token, { bloodGroup: params.bloodGroup, radiusKm: Number(params.radiusKm ?? 10), eligibleOnly: params.eligibleOnly !== 'false', availableNow: params.availableNow !== 'false' }), donorService.listRequests(token)]).then(([found, current]) => { setDonors(found); setRequests(current); }).catch(() => setError('Could not load donors.')).finally(() => setLoading(false)); }, [params, token]);
  const isRequested = (id?: string) => requests.some((r) => r.donorId === id && r.status === 'pending');
  const toggle = async (donor: Donor) => { if (!donor.id) return; if (isRequested(donor.id)) { await donorService.cancelRequest(token, donor.id); setRequests((old) => old.filter((r) => r.donorId !== donor.id)); } else { const item = await donorService.request(token, donor.id); setRequests((old) => [item, ...old]); } };
  return <SafeAreaView style={styles.safe}><AppHeader title="Matching Donors" subtitle={`${donors.length} donors found`} rightElement={<TouchableOpacity onPress={() => { void exportDonorsPdf(donors); }} accessibilityLabel="Export matching donors PDF"><Ionicons name="document-text-outline" size={24} color={colors.primary} /></TouchableOpacity>} /><ScrollView contentContainerStyle={styles.content}>{loading ? <ActivityIndicator color={colors.primary} size="large" /> : error ? <Text style={styles.error}>{error}</Text> : donors.length === 0 ? <View style={styles.empty}><Ionicons name="people-outline" size={48} color={colors.textMuted} /><Text style={styles.heading}>No donors within {params.radiusKm ?? 10} km</Text><Text style={styles.muted}>Increase the radius and try again.</Text></View> : donors.map((donor) => <View style={styles.card} key={`${donor.name}-${donor.distanceKm}`}><View style={styles.top}><View style={styles.avatar}><Text style={styles.avatarText}>{donor.avatarInitials}</Text></View><View style={styles.nameBlock}><Text style={styles.name}>{donor.name}</Text><Text style={styles.muted}>{donor.distanceKm} km away • {donor.bloodGroup}</Text></View><View style={[styles.badge, { backgroundColor: donor.eligible ? colors.successSoft : colors.dangerSoft }]}><Text style={{ color: donor.eligible ? colors.success : colors.danger, fontSize: 11, fontWeight: '800' }}>{donor.eligible ? 'Eligible' : 'Not eligible'}</Text></View></View><Text style={styles.muted}>{donor.available ? 'Available now' : 'Currently unavailable'}</Text><TouchableOpacity style={styles.profileLink} onPress={() => router.push({ pathname: '/profile/public-preview', params: { donorName: donor.name, donorBloodGroup: donor.bloodGroup, donorAvailable: String(donor.available), donorEligible: String(donor.eligible), donorDistance: String(donor.distanceKm) } })}><Ionicons name="person-circle-outline" size={18} color={colors.primary} /><Text style={styles.profileLinkText}>View Profile</Text></TouchableOpacity><View style={styles.actions}><TouchableOpacity disabled={!donor.eligible} style={[styles.request, !donor.eligible && styles.disabled]} onPress={() => { void toggle(donor); }}><Text style={styles.requestText}>{isRequested(donor.id) ? 'Cancel request' : 'Request'}</Text></TouchableOpacity><TouchableOpacity style={styles.chat} onPress={() => router.push({ pathname: '/chat', params: { donorId: donor.id, donorName: donor.name } })}><Ionicons name="chatbubble-outline" size={18} color={colors.primary} /><Text style={styles.chatText}>Chat</Text></TouchableOpacity></View></View>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.md, paddingBottom: 40 }, card: { backgroundColor: colors.card, padding: spacing.md, borderRadius: borderRadius.md, marginBottom: spacing.md }, top: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primaryDark, fontWeight: '800' }, nameBlock: { flex: 1, minWidth: 0 }, name: { color: colors.text, fontWeight: '800', fontSize: 16, flexShrink: 1 }, muted: { color: colors.textMuted, marginTop: 4, flexShrink: 1 }, badge: { padding: 6, borderRadius: borderRadius.sm, marginLeft: spacing.xs, flexShrink: 0 }, profileLink: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: spacing.sm }, profileLinkText: { color: colors.primary, fontWeight: '800' }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, request: { flex: 1, minWidth: 140, minHeight: 44, borderRadius: borderRadius.sm, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, requestText: { color: colors.textInverted, fontWeight: '800', textAlign: 'center' }, chat: { minWidth: 90, minHeight: 44, borderRadius: borderRadius.sm, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 }, chatText: { color: colors.primary, fontWeight: '800' }, disabled: { opacity: 0.45 }, empty: { alignItems: 'center', paddingTop: 80, gap: spacing.sm }, heading: { color: colors.text, fontSize: 18, fontWeight: '800', textAlign: 'center' }, error: { color: colors.danger, textAlign: 'center' } });
