import React, { useEffect, useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Swipeable } from 'react-native-gesture-handler';
import { Ionicons } from '@expo/vector-icons';
import { AppHeader } from '@/components/AppHeader';
import { colors, spacing, borderRadius } from '@/theme';
import { useAuth } from '@/features/auth/context/AuthContext';
import { donorService } from '../services/donorService';
import { exportNotificationsPdf } from '../utils/pdf';
import type { NotificationItem } from '../types';
export default function NotificationsScreen() {
  const { token } = useAuth(); const [items, setItems] = useState<NotificationItem[]>([]);
  useEffect(() => { void donorService.listNotifications(token).then(setItems); }, [token]);
  const patch = (id: string, action: () => Promise<void>) => { void action().then(() => setItems((old) => old.map((n) => n._id === id ? { ...n, read: true } : n))); };
  const actions = (item: NotificationItem, side: 'left' | 'right') => side === 'right' ? <View style={styles.swipeDelete}><Ionicons name="trash-outline" size={22} color={colors.textInverted} /></View> : (item.type === 'emergency' || item.type === 'donor_request') ? <View style={styles.swipeActions}><TouchableOpacity style={styles.swipeAccept} onPress={() => patch(item._id, () => donorService.respond(token, item._id, 'accepted'))}><Text style={styles.swipeText}>Accept</Text></TouchableOpacity><TouchableOpacity style={styles.swipeDecline} onPress={() => patch(item._id, () => donorService.respond(token, item._id, 'declined'))}><Text style={styles.swipeText}>Decline</Text></TouchableOpacity></View> : null;
  return <SafeAreaView style={styles.safe}><AppHeader title="Notifications" rightElement={<TouchableOpacity onPress={() => { void exportNotificationsPdf(items); }} accessibilityLabel="Export notifications PDF"><Ionicons name="document-text-outline" size={23} color={colors.primary} /></TouchableOpacity>} /><View style={styles.toolbar}><Text style={styles.count}>{items.filter((n) => !n.read).length} unread</Text><TouchableOpacity onPress={() => { void donorService.readAll(token).then(() => setItems((old) => old.map((n) => ({ ...n, read: true })))); }}><Text style={styles.link}>Mark all read</Text></TouchableOpacity></View><ScrollView contentContainerStyle={styles.content}>{items.length === 0 ? <View style={styles.empty}><Ionicons name="checkmark-circle-outline" size={54} color={colors.success} /><Text style={styles.heading}>{'You\'re all caught up'}</Text></View> : items.map((item) => <Swipeable key={item._id} renderLeftActions={() => actions(item, 'left')} renderRightActions={() => actions(item, 'right')} onSwipeableOpen={(direction) => { if (direction === 'right') void donorService.deleteNotification(token, item._id).then(() => setItems((old) => old.filter((n) => n._id !== item._id))); }}><View style={[styles.card, !item.read && styles.unread]}><TouchableOpacity style={styles.row} onPress={() => patch(item._id, () => donorService.readNotification(token, item._id))}><Ionicons name={item.type === 'emergency' ? 'alert-circle' : item.type === 'accepted' ? 'checkmark-circle' : item.type === 'campaign' ? 'calendar' : 'person-add'} size={28} color={item.type === 'emergency' ? colors.danger : colors.primary} /><View style={{ flex: 1, marginLeft: spacing.sm }}><Text style={styles.title}>{item.title}</Text><Text style={styles.details}>{item.details}</Text><Text style={styles.when}>{new Date(item.createdAt).toLocaleString()}</Text></View><TouchableOpacity onPress={() => { void donorService.deleteNotification(token, item._id).then(() => setItems((old) => old.filter((n) => n._id !== item._id))); }} accessibilityLabel="Delete notification"><Ionicons name="trash-outline" size={20} color={colors.textMuted} /></TouchableOpacity></TouchableOpacity>{(item.type === 'emergency' || item.type === 'donor_request') && <View style={styles.response}><TouchableOpacity onPress={() => patch(item._id, () => donorService.respond(token, item._id, 'accepted'))}><Text style={styles.accept}>Accept</Text></TouchableOpacity><TouchableOpacity onPress={() => patch(item._id, () => donorService.respond(token, item._id, 'declined'))}><Text style={styles.decline}>Decline</Text></TouchableOpacity></View>}</View></Swipeable>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, toolbar: { flexDirection: 'row', justifyContent: 'space-between', padding: spacing.md }, count: { color: colors.textSecondary, fontWeight: '700' }, link: { color: colors.primary, fontWeight: '800' }, content: { padding: spacing.md }, card: { backgroundColor: colors.card, borderRadius: borderRadius.md, padding: spacing.md, marginBottom: spacing.sm }, unread: { borderLeftWidth: 4, borderLeftColor: colors.primary, backgroundColor: colors.primaryTonal }, row: { flexDirection: 'row', alignItems: 'flex-start' }, title: { color: colors.text, fontWeight: '800' }, details: { color: colors.textSecondary, marginTop: 4 }, when: { color: colors.textMuted, fontSize: 11, marginTop: 5 }, response: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.sm, paddingTop: spacing.sm, flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.lg }, accept: { color: colors.success, fontWeight: '800' }, decline: { color: colors.danger, fontWeight: '800' }, swipeActions: { flexDirection: 'row', marginBottom: spacing.sm }, swipeAccept: { width: 88, backgroundColor: colors.success, justifyContent: 'center', alignItems: 'center' }, swipeDecline: { width: 88, backgroundColor: colors.danger, justifyContent: 'center', alignItems: 'center' }, swipeDelete: { width: 76, marginBottom: spacing.sm, backgroundColor: colors.danger, justifyContent: 'center', alignItems: 'center' }, swipeText: { color: colors.textInverted, fontWeight: '800' }, empty: { alignItems: 'center', paddingTop: 100, gap: spacing.md }, heading: { color: colors.text, fontWeight: '800', fontSize: 18 } });
