export const inventoryStrings = {
  en: {
    title: 'Blood stock',
    unitsAvailable: 'units available',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    out: 'Out of stock',
    offlineDemo: 'Offline demo data',
    noBanks: 'No blood banks found',
    tryAgain: 'Try again',
    loading: 'Loading blood banks',
    searchPlaceholder: 'Search blood banks',
    nearest: 'Nearest',
    openNow: 'Open now',
    highStock: 'High stock',
    open: 'Open',
    closed: 'Closed',
    getDirections: 'Get Directions',
    call: 'Call',
    stock: 'Stock',
    details: 'Bank details',
    locationPermission: 'Location permission was not granted. Showing Colombo blood banks.',
    subtitle: 'Find nearby blood availability',
    mapLabel: 'Map of nearby blood banks',
    searchLabel: 'Search blood banks by name or district',
    all: 'All',
    allBloodGroups: 'All blood groups',
    bloodGroup: 'Blood group',
    openDetails: 'Open details for',
    distanceUnavailable: 'Distance unavailable',
    mapsError: 'Could not open maps.',
    callError: 'Could not start the phone call.',
  },
  si: {},
  ta: {},
} as const;
