export const susStrings = {
  en: {
    title: 'Help us improve',
    question: 'The app makes it easy to find blood support.',
    submit: 'Send feedback',
    thanks: 'Thank you for your feedback',
    offlineDemo: 'Offline demo mode: feedback will be sent when you are online.',
    error: 'Feedback could not be submitted',
    communityTitle: 'Community',
    activityCount: 'members connected',
    promptTitle: 'How easy was the app to use?',
    promptBody: 'Your feedback helps us make blood support easier for everyone.',
    openSurvey: 'Share your feedback',
    scoreLabels: ['Strongly disagree', 'Disagree', 'Neither agree nor disagree', 'Agree', 'Strongly agree'],
    frequencyStatement: 'I would like to use this system frequently',
    agree: 'Agree',
    disagree: 'Disagree',
    close: 'Close',
    submitting: 'Submitting',
    submitSuccess: 'Thank you for your feedback',
    submitError: 'Feedback could not be submitted.',
    communityMemberCount: '1,248',
    closeIcon: '×',
    successIcon: '✓',
  },
  si: {},
  ta: {},
} as const;
