export const campaignsStrings = {
  en: {
    title: 'Blood donation campaigns',
    register: 'Register',
    registered: 'Registered',
    spotsRemaining: 'spots remaining',
    offlineDemo: 'Offline demo data',
    noCampaigns: 'No upcoming campaigns',
    tryAgain: 'Try again',
    loading: 'Loading campaigns',
    subtitle: 'Find a blood drive near you',
    registerPrompt: (title: string) => `Do you want to register for ${title}?`,
    cancel: 'Cancel',
    yesRegister: 'Yes, Register',
    registrationFailed: 'Registration could not be completed.',
    alreadyRegistered: 'You are already registered for this campaign.',
    campaignFull: 'This campaign is full.',
    successTitle: 'Registration confirmed',
    referenceNumber: 'Reference number',
    backToCampaigns: 'Back to Campaigns',
    date: 'Date',
    venue: 'Venue',
    organizer: 'Organizer',
    imageLabel: 'Campaign image',
    brand: 'LIFELINE LK',
    registering: 'Registering…',
    registerFor: (title: string) => `Register for ${title}`,
  },
  si: {},
  ta: {},
} as const;
